
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
# for offset=0. speed_to_erpm_gain = num_motor_poles*60/circumference_wheel_in_meters
speed_to_erpm_gain: 4614 # 강태 : 변경 => -4614 to 4614
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: -0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 2.0 # radians/second
servo_smoother_rate: 150.0 # messages/sec

# # servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 2.0 # meters/second^2
throttle_smoother_rate: 100.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -1.2135
steering_angle_to_servo_offset: 0.5304

# publish odom to base link tf
vesc_to_odom/publish_tf: true

# car wheelbase is about 25cm 
wheelbase: .25

vesc_driver:
  port: /dev/ttyVesc
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 20.0
  brake_min: -2000.0
  brake_max: 2000.0
  speed_min: -3000
  speed_max: 3000
  position_min: 0.0
  position_max: 0.0
  # servo_min: 0.15
  # servo_max: 0.85
  servo_min: 0.2
  servo_max: 0.8