# 적당한 cali - 가쪽 왜곡 덜함

# 이미지 크기 및 카메라 이름
image_width: 640          # 픽셀 너비
image_height: 480         # 픽셀 높이
camera_name: usb_cam

# 내부 파라미터 (K)
camera_matrix:
  rows: 3
  cols: 3
  data: [422.037858, 0.000000, 245.895397, 0.000000, 435.589734, 163.625535, 0.000000, 0.000000, 1.000000]

# 왜곡 모델/계수
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.289296, 0.061035, 0.001786, 0.015238, 0.000000]

# 직교화/투영 행렬
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [333.094543, 0.000000, 229.784726, 0.000000, 0.000000, 372.516754, 146.696473, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
